# This file is machine-generated - editing it directly is not advised

julia_version = "1.7.3"
manifest_format = "2.0"

[[deps.upstream]]
git-tree-sha1 = "ab3bef92dbfdeb321be3845c057fb2d24f6a32c7"
repo-rev = "main"
repo-url = "https://github.com/aaronpeikert/upstream.jl"
uuid = "dfa7368c-5b78-4bda-9dde-69676b7aee7c"
version = "0.1.0"
