name: CI_latest
on:
  push:
    branches: '*'
    tags: '*'
  workflow_dispatch:
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    env:
      JULIA_NUM_THREADS: 8
    strategy:
      fail-fast: true
      matrix:
        version:
          - '1.7.3'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      #- name: Clone Upstream
      #  uses: actions/checkout@v2
      #  with:
      #    repository: 'aaronpeikert/upstream.jl'
      #    ref: 'main'
          # path: downstream
      - uses: julia-actions/julia-buildpkg@v1
      - name: Install correct version of upstream package
        shell: julia --color=yes --project {0}
        run: |
          using Pkg
          try
            # force it to use this PR's version of the package
            Pkg.add(url = "https://github.com/aaronpeikert/upstream.jl", rev = "main")
            # Pkg.test(coverage=true)  # resolver may fail with test time deps
          catch err
            err isa Pkg.Resolve.ResolverError || rethrow()
            # If we can't resolve that means this is incompatible by SemVer and this is fine
            # It means we marked this as a breaking change, so we don't need to worry about
            # Mistakenly introducing a breaking change, as we have intentionally made one
            @info "Not compatible with this release. No problem." exception=err
            exit(0)  # Exit immediately, as a success
          end
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v2
        with:
          file: lcov.info